//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN_Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Карточка гражданина.
    /// </summary>
    //  *** Start programmer edit section *** (КарточкаГражданина CustomAttributes)

    //  *** End programmer edit section *** (КарточкаГражданина CustomAttributes)
    [AutoAltered()]
    [Caption("Карточка гражданина")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КарточкаГражданинаE", new string[] {
            "ДатаОбращения as \'Дата обращения\'",
            "Личность as \'Личность\'",
            "Личность.ФИО as \'ФИО\'"})]
    [AssociatedDetailViewAttribute("КарточкаГражданинаE", "ПередачаКарточки", "ПередачаКарточкиE", true, "", "Передача карточки", true, new string[] {
            ""})]
    [View("КарточкаГражданинаL", new string[] {
            "ДатаОбращения as \'Дата обращения\'",
            "Личность.ФИО as \'ФИО\'"})]
    public class КарточкаГражданина : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОбращения;
        
        private IIS.CZN_Prilozhenie.Личность fЛичность;
        
        private IIS.CZN_Prilozhenie.DetailArrayOfПередачаКарточки fПередачаКарточки;
        
        //  *** Start programmer edit section *** (КарточкаГражданина CustomMembers)

        //  *** End programmer edit section *** (КарточкаГражданина CustomMembers)

        
        /// <summary>
        /// ДатаОбращения.
        /// </summary>
        //  *** Start programmer edit section *** (КарточкаГражданина.ДатаОбращения CustomAttributes)

        //  *** End programmer edit section *** (КарточкаГражданина.ДатаОбращения CustomAttributes)
        public virtual System.DateTime ДатаОбращения
        {
            get
            {
                //  *** Start programmer edit section *** (КарточкаГражданина.ДатаОбращения Get start)

                //  *** End programmer edit section *** (КарточкаГражданина.ДатаОбращения Get start)
                System.DateTime result = this.fДатаОбращения;
                //  *** Start programmer edit section *** (КарточкаГражданина.ДатаОбращения Get end)

                //  *** End programmer edit section *** (КарточкаГражданина.ДатаОбращения Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (КарточкаГражданина.ДатаОбращения Set start)

                //  *** End programmer edit section *** (КарточкаГражданина.ДатаОбращения Set start)
                this.fДатаОбращения = value;
                //  *** Start programmer edit section *** (КарточкаГражданина.ДатаОбращения Set end)

                //  *** End programmer edit section *** (КарточкаГражданина.ДатаОбращения Set end)
            }
        }
        
        /// <summary>
        /// Карточка гражданина.
        /// </summary>
        //  *** Start programmer edit section *** (КарточкаГражданина.Личность CustomAttributes)

        //  *** End programmer edit section *** (КарточкаГражданина.Личность CustomAttributes)
        [NotNull()]
        public virtual IIS.CZN_Prilozhenie.Личность Личность
        {
            get
            {
                //  *** Start programmer edit section *** (КарточкаГражданина.Личность Get start)

                //  *** End programmer edit section *** (КарточкаГражданина.Личность Get start)
                IIS.CZN_Prilozhenie.Личность result = this.fЛичность;
                //  *** Start programmer edit section *** (КарточкаГражданина.Личность Get end)

                //  *** End programmer edit section *** (КарточкаГражданина.Личность Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (КарточкаГражданина.Личность Set start)

                //  *** End programmer edit section *** (КарточкаГражданина.Личность Set start)
                this.fЛичность = value;
                //  *** Start programmer edit section *** (КарточкаГражданина.Личность Set end)

                //  *** End programmer edit section *** (КарточкаГражданина.Личность Set end)
            }
        }
        
        /// <summary>
        /// Карточка гражданина.
        /// </summary>
        //  *** Start programmer edit section *** (КарточкаГражданина.ПередачаКарточки CustomAttributes)

        //  *** End programmer edit section *** (КарточкаГражданина.ПередачаКарточки CustomAttributes)
        public virtual IIS.CZN_Prilozhenie.DetailArrayOfПередачаКарточки ПередачаКарточки
        {
            get
            {
                //  *** Start programmer edit section *** (КарточкаГражданина.ПередачаКарточки Get start)

                //  *** End programmer edit section *** (КарточкаГражданина.ПередачаКарточки Get start)
                if ((this.fПередачаКарточки == null))
                {
                    this.fПередачаКарточки = new IIS.CZN_Prilozhenie.DetailArrayOfПередачаКарточки(this);
                }
                IIS.CZN_Prilozhenie.DetailArrayOfПередачаКарточки result = this.fПередачаКарточки;
                //  *** Start programmer edit section *** (КарточкаГражданина.ПередачаКарточки Get end)

                //  *** End programmer edit section *** (КарточкаГражданина.ПередачаКарточки Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (КарточкаГражданина.ПередачаКарточки Set start)

                //  *** End programmer edit section *** (КарточкаГражданина.ПередачаКарточки Set start)
                this.fПередачаКарточки = value;
                //  *** Start programmer edit section *** (КарточкаГражданина.ПередачаКарточки Set end)

                //  *** End programmer edit section *** (КарточкаГражданина.ПередачаКарточки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КарточкаГражданинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КарточкаГражданинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КарточкаГражданинаE", typeof(IIS.CZN_Prilozhenie.КарточкаГражданина));
                }
            }
            
            /// <summary>
            /// "КарточкаГражданинаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КарточкаГражданинаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КарточкаГражданинаL", typeof(IIS.CZN_Prilozhenie.КарточкаГражданина));
                }
            }
        }
    }
}
