//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN_Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Личность.
    /// </summary>
    //  *** Start programmer edit section *** (Личность CustomAttributes)

    //  *** End programmer edit section *** (Личность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЛичностьE", new string[] {
            "ФИО as \'ФИО\'",
            "Возраст as \'Возраст\'"})]
    [AssociatedDetailViewAttribute("ЛичностьE", "ОсобенностиЛичности", "ОсобенностиЛичностиE", true, "", "Особенности личности", true, new string[] {
            ""})]
    [View("ЛичностьL", new string[] {
            "ФИО as \'ФИО\'",
            "Возраст as \'Возраст\'"})]
    public class Личность : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private int fВозраст;
        
        private IIS.CZN_Prilozhenie.DetailArrayOfОсобенностиЛичности fОсобенностиЛичности;
        
        //  *** Start programmer edit section *** (Личность CustomMembers)

        //  *** End programmer edit section *** (Личность CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        //  *** Start programmer edit section *** (Личность.ФИО CustomAttributes)

        //  *** End programmer edit section *** (Личность.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                //  *** Start programmer edit section *** (Личность.ФИО Get start)

                //  *** End programmer edit section *** (Личность.ФИО Get start)
                string result = this.fФИО;
                //  *** Start programmer edit section *** (Личность.ФИО Get end)

                //  *** End programmer edit section *** (Личность.ФИО Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Личность.ФИО Set start)

                //  *** End programmer edit section *** (Личность.ФИО Set start)
                this.fФИО = value;
                //  *** Start programmer edit section *** (Личность.ФИО Set end)

                //  *** End programmer edit section *** (Личность.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Возраст.
        /// </summary>
        //  *** Start programmer edit section *** (Личность.Возраст CustomAttributes)

        //  *** End programmer edit section *** (Личность.Возраст CustomAttributes)
        public virtual int Возраст
        {
            get
            {
                //  *** Start programmer edit section *** (Личность.Возраст Get start)

                //  *** End programmer edit section *** (Личность.Возраст Get start)
                int result = this.fВозраст;
                //  *** Start programmer edit section *** (Личность.Возраст Get end)

                //  *** End programmer edit section *** (Личность.Возраст Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Личность.Возраст Set start)

                //  *** End programmer edit section *** (Личность.Возраст Set start)
                this.fВозраст = value;
                //  *** Start programmer edit section *** (Личность.Возраст Set end)

                //  *** End programmer edit section *** (Личность.Возраст Set end)
            }
        }
        
        /// <summary>
        /// Личность.
        /// </summary>
        //  *** Start programmer edit section *** (Личность.ОсобенностиЛичности CustomAttributes)

        //  *** End programmer edit section *** (Личность.ОсобенностиЛичности CustomAttributes)
        public virtual IIS.CZN_Prilozhenie.DetailArrayOfОсобенностиЛичности ОсобенностиЛичности
        {
            get
            {
                //  *** Start programmer edit section *** (Личность.ОсобенностиЛичности Get start)

                //  *** End programmer edit section *** (Личность.ОсобенностиЛичности Get start)
                if ((this.fОсобенностиЛичности == null))
                {
                    this.fОсобенностиЛичности = new IIS.CZN_Prilozhenie.DetailArrayOfОсобенностиЛичности(this);
                }
                IIS.CZN_Prilozhenie.DetailArrayOfОсобенностиЛичности result = this.fОсобенностиЛичности;
                //  *** Start programmer edit section *** (Личность.ОсобенностиЛичности Get end)

                //  *** End programmer edit section *** (Личность.ОсобенностиЛичности Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Личность.ОсобенностиЛичности Set start)

                //  *** End programmer edit section *** (Личность.ОсобенностиЛичности Set start)
                this.fОсобенностиЛичности = value;
                //  *** Start programmer edit section *** (Личность.ОсобенностиЛичности Set end)

                //  *** End programmer edit section *** (Личность.ОсобенностиЛичности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЛичностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛичностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛичностьE", typeof(IIS.CZN_Prilozhenie.Личность));
                }
            }
            
            /// <summary>
            /// "ЛичностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛичностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛичностьL", typeof(IIS.CZN_Prilozhenie.Личность));
                }
            }
        }
    }
}
