//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN_Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Особенности личности.
    /// </summary>
    //  *** Start programmer edit section *** (ОсобенностиЛичности CustomAttributes)

    //  *** End programmer edit section *** (ОсобенностиЛичности CustomAttributes)
    [AutoAltered()]
    [Caption("Особенности личности")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОсобенностиЛичностиE", new string[] {
            "ОсобенностиЛица as \'Особенности лица\'",
            "ОсобенностиФигуры as \'Особенности фигуры\'",
            "ОсобенностиХарактера as \'Особенности характера\'"})]
    public class ОсобенностиЛичности : ICSSoft.STORMNET.DataObject
    {
        
        private string fОсобенностиЛица;
        
        private string fОсобенностиФигуры;
        
        private string fОсобенностиХарактера;
        
        private IIS.CZN_Prilozhenie.Личность fЛичность;
        
        //  *** Start programmer edit section *** (ОсобенностиЛичности CustomMembers)

        //  *** End programmer edit section *** (ОсобенностиЛичности CustomMembers)

        
        /// <summary>
        /// ОсобенностиЛица.
        /// </summary>
        //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиЛица CustomAttributes)

        //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиЛица CustomAttributes)
        [StrLen(255)]
        public virtual string ОсобенностиЛица
        {
            get
            {
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиЛица Get start)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиЛица Get start)
                string result = this.fОсобенностиЛица;
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиЛица Get end)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиЛица Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиЛица Set start)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиЛица Set start)
                this.fОсобенностиЛица = value;
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиЛица Set end)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиЛица Set end)
            }
        }
        
        /// <summary>
        /// ОсобенностиФигуры.
        /// </summary>
        //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиФигуры CustomAttributes)

        //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиФигуры CustomAttributes)
        [StrLen(255)]
        public virtual string ОсобенностиФигуры
        {
            get
            {
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиФигуры Get start)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиФигуры Get start)
                string result = this.fОсобенностиФигуры;
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиФигуры Get end)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиФигуры Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиФигуры Set start)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиФигуры Set start)
                this.fОсобенностиФигуры = value;
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиФигуры Set end)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиФигуры Set end)
            }
        }
        
        /// <summary>
        /// ОсобенностиХарактера.
        /// </summary>
        //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиХарактера CustomAttributes)

        //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиХарактера CustomAttributes)
        [StrLen(255)]
        public virtual string ОсобенностиХарактера
        {
            get
            {
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиХарактера Get start)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиХарактера Get start)
                string result = this.fОсобенностиХарактера;
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиХарактера Get end)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиХарактера Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиХарактера Set start)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиХарактера Set start)
                this.fОсобенностиХарактера = value;
                //  *** Start programmer edit section *** (ОсобенностиЛичности.ОсобенностиХарактера Set end)

                //  *** End programmer edit section *** (ОсобенностиЛичности.ОсобенностиХарактера Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CZN_Prilozhenie.Личность.
        /// </summary>
        //  *** Start programmer edit section *** (ОсобенностиЛичности.Личность CustomAttributes)

        //  *** End programmer edit section *** (ОсобенностиЛичности.Личность CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.CZN_Prilozhenie.Личность Личность
        {
            get
            {
                //  *** Start programmer edit section *** (ОсобенностиЛичности.Личность Get start)

                //  *** End programmer edit section *** (ОсобенностиЛичности.Личность Get start)
                IIS.CZN_Prilozhenie.Личность result = this.fЛичность;
                //  *** Start programmer edit section *** (ОсобенностиЛичности.Личность Get end)

                //  *** End programmer edit section *** (ОсобенностиЛичности.Личность Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ОсобенностиЛичности.Личность Set start)

                //  *** End programmer edit section *** (ОсобенностиЛичности.Личность Set start)
                this.fЛичность = value;
                //  *** Start programmer edit section *** (ОсобенностиЛичности.Личность Set end)

                //  *** End programmer edit section *** (ОсобенностиЛичности.Личность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОсобенностиЛичностиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОсобенностиЛичностиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОсобенностиЛичностиE", typeof(IIS.CZN_Prilozhenie.ОсобенностиЛичности));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОсобенностиЛичности.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfОсобенностиЛичности CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfОсобенностиЛичности CustomAttributes)
    public class DetailArrayOfОсобенностиЛичности : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.CZN_Prilozhenie.DetailArrayOfОсобенностиЛичности members)

        //  *** End programmer edit section *** (IIS.CZN_Prilozhenie.DetailArrayOfОсобенностиЛичности members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОсобенностиЛичности by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОсобенностиЛичности.
        /// </summary>
        public DetailArrayOfОсобенностиЛичности(IIS.CZN_Prilozhenie.Личность fЛичность) : 
                base(typeof(ОсобенностиЛичности), ((ICSSoft.STORMNET.DataObject)(fЛичность)))
        {
        }
        
        public IIS.CZN_Prilozhenie.ОсобенностиЛичности this[int index]
        {
            get
            {
                return ((IIS.CZN_Prilozhenie.ОсобенностиЛичности)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CZN_Prilozhenie.ОсобенностиЛичности dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
