//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.CZN_Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Передача карточки.
    /// </summary>
    //  *** Start programmer edit section *** (ПередачаКарточки CustomAttributes)

    //  *** End programmer edit section *** (ПередачаКарточки CustomAttributes)
    [AutoAltered()]
    [Caption("Передача карточки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПередачаКарточкиE", new string[] {
            "ДатаПередачи as \'Дата передачи\'",
            "Сотрудник as \'Сотрудник\'"})]
    public class ПередачаКарточки : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПередачи;
        
        private string fСотрудник;
        
        private IIS.CZN_Prilozhenie.КарточкаГражданина fКарточкаГражданина;
        
        //  *** Start programmer edit section *** (ПередачаКарточки CustomMembers)

        //  *** End programmer edit section *** (ПередачаКарточки CustomMembers)

        
        /// <summary>
        /// ДатаПередачи.
        /// </summary>
        //  *** Start programmer edit section *** (ПередачаКарточки.ДатаПередачи CustomAttributes)

        //  *** End programmer edit section *** (ПередачаКарточки.ДатаПередачи CustomAttributes)
        public virtual System.DateTime ДатаПередачи
        {
            get
            {
                //  *** Start programmer edit section *** (ПередачаКарточки.ДатаПередачи Get start)

                //  *** End programmer edit section *** (ПередачаКарточки.ДатаПередачи Get start)
                System.DateTime result = this.fДатаПередачи;
                //  *** Start programmer edit section *** (ПередачаКарточки.ДатаПередачи Get end)

                //  *** End programmer edit section *** (ПередачаКарточки.ДатаПередачи Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПередачаКарточки.ДатаПередачи Set start)

                //  *** End programmer edit section *** (ПередачаКарточки.ДатаПередачи Set start)
                this.fДатаПередачи = value;
                //  *** Start programmer edit section *** (ПередачаКарточки.ДатаПередачи Set end)

                //  *** End programmer edit section *** (ПередачаКарточки.ДатаПередачи Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        //  *** Start programmer edit section *** (ПередачаКарточки.Сотрудник CustomAttributes)

        //  *** End programmer edit section *** (ПередачаКарточки.Сотрудник CustomAttributes)
        [StrLen(255)]
        public virtual string Сотрудник
        {
            get
            {
                //  *** Start programmer edit section *** (ПередачаКарточки.Сотрудник Get start)

                //  *** End programmer edit section *** (ПередачаКарточки.Сотрудник Get start)
                string result = this.fСотрудник;
                //  *** Start programmer edit section *** (ПередачаКарточки.Сотрудник Get end)

                //  *** End programmer edit section *** (ПередачаКарточки.Сотрудник Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПередачаКарточки.Сотрудник Set start)

                //  *** End programmer edit section *** (ПередачаКарточки.Сотрудник Set start)
                this.fСотрудник = value;
                //  *** Start programmer edit section *** (ПередачаКарточки.Сотрудник Set end)

                //  *** End programmer edit section *** (ПередачаКарточки.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.CZN_Prilozhenie.КарточкаГражданина.
        /// </summary>
        //  *** Start programmer edit section *** (ПередачаКарточки.КарточкаГражданина CustomAttributes)

        //  *** End programmer edit section *** (ПередачаКарточки.КарточкаГражданина CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.CZN_Prilozhenie.КарточкаГражданина КарточкаГражданина
        {
            get
            {
                //  *** Start programmer edit section *** (ПередачаКарточки.КарточкаГражданина Get start)

                //  *** End programmer edit section *** (ПередачаКарточки.КарточкаГражданина Get start)
                IIS.CZN_Prilozhenie.КарточкаГражданина result = this.fКарточкаГражданина;
                //  *** Start programmer edit section *** (ПередачаКарточки.КарточкаГражданина Get end)

                //  *** End programmer edit section *** (ПередачаКарточки.КарточкаГражданина Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (ПередачаКарточки.КарточкаГражданина Set start)

                //  *** End programmer edit section *** (ПередачаКарточки.КарточкаГражданина Set start)
                this.fКарточкаГражданина = value;
                //  *** Start programmer edit section *** (ПередачаКарточки.КарточкаГражданина Set end)

                //  *** End programmer edit section *** (ПередачаКарточки.КарточкаГражданина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПередачаКарточкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПередачаКарточкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПередачаКарточкиE", typeof(IIS.CZN_Prilozhenie.ПередачаКарточки));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ПередачаКарточки.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfПередачаКарточки CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfПередачаКарточки CustomAttributes)
    public class DetailArrayOfПередачаКарточки : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.CZN_Prilozhenie.DetailArrayOfПередачаКарточки members)

        //  *** End programmer edit section *** (IIS.CZN_Prilozhenie.DetailArrayOfПередачаКарточки members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ПередачаКарточки by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ПередачаКарточки.
        /// </summary>
        public DetailArrayOfПередачаКарточки(IIS.CZN_Prilozhenie.КарточкаГражданина fКарточкаГражданина) : 
                base(typeof(ПередачаКарточки), ((ICSSoft.STORMNET.DataObject)(fКарточкаГражданина)))
        {
        }
        
        public IIS.CZN_Prilozhenie.ПередачаКарточки this[int index]
        {
            get
            {
                return ((IIS.CZN_Prilozhenie.ПередачаКарточки)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.CZN_Prilozhenie.ПередачаКарточки dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
